/*
20141130 Scott Havens
Create a table that stores the stations to download, the length of time, and whose stations they are
This table wil be how the weather data is downloaded.

Data length of NULL will not crop the length of the table

When client='xxxx' is passed to accessWeather, the variables from the wxvars for the station will be returned.  This
allows more customization than before
*/

CREATE TABLE IF NOT EXISTS tbl_stations (
	station_id VARCHAR(10),
    client VARCHAR(100),
	source VARCHAR(50),
	PRIMARY KEY (station_id, client, source)
);

-- BOISE RIVER BASIN
REPLACE INTO tbl_stations VALUES
('ARAI1','BRB'),
('ARKI1','BRB'),
('ATAI1','BRB'),
('ATLI1','BRB'),
('AU912','BRB'),
('BASI1','BRB'),
('BCFI1','BRB'),
('BNRI1','BRB'),
('BOGI1','BRB'),
('BOII','BRB'),
('BRFI1','BRB'),
('BSKI1','BRB'),
('C0406','BRB'),
('C0810','BRB'),
('CCDI1','BRB'),
('COZI1','BRB'),
('CVAI1','BRB'),
('D8224','BRB'),
('D8425','BRB'),
('DEDI1','BRB'),
('DEHI1','BRB'),
('DHDI1','BRB'),
('FAFI','BRB'),
('FLEI1','BRB'),
('GAVI1','BRB'),
('GGSI1','BRB'),
('GLNI1','BRB'),
('GLSI1','BRB'),
('HPFI1','BRB'),
('ITD36','BRB'),
('ITD38','BRB'),
('ITD42','BRB'),
('ITD51','BRB'),
('ITD53','BRB'),
('ITD71','BRB'),
('JKPI1','BRB'),
('KSNT','BRB'),
('KU76','BRB'),
('LTAI1','BRB'),
('ORRI1','BRB'),
('PNFI1','BRB'),
('PRAI1','BRB'),
('PRLI1','BRB'),
('SCR','BRB'),
('SLDMS','BRB'),
('SLDMT','BRB'),
('SRSI1','BRB'),
('STNI1','BRB'),
('SVT','BRB'),
('TCFI1','BRB'),
('TR216','BRB'),
('TRMI1','BRB'),
('TS718','BRB'),
('TS960','BRB'),
('TS961','BRB'),
('TS962','BRB'),
('TTSID','BRB'),
('UP174','BRB'),
('UP237','BRB'),
('VNNI1','BRB'),
('WAGI1','BRB'),
('YFFI1','BRB'),

-- TUOLUMNE
('A1276','TUOL'),
('A1279','TUOL'),
('AGPC1','TUOL'),
('AHIC1','TUOL'),
('AS728','TUOL'),
('BPOC1','TUOL'),
('C2998','TUOL'),
('C4643','TUOL'),
('CEVC1','TUOL'),
('CNFC1','TUOL'),
('CQ160','TUOL'),
('CRVC1','TUOL'),
('D5868','TUOL'),
('DDMC1','TUOL'),
('DPPC1','TUOL'),
('E3821','TUOL'),
('EPWC1','TUOL'),
('ERYC1','TUOL'),
('GFTC1','TUOL'),
('GNLC1','TUOL'),
('GRMC1','TUOL'),
('HDMCA','TUOL'),
('HHWC1','TUOL'),
('HRSC1','TUOL'),
('JEMC1','TUOL'),
('JMTC1','TUOL'),
('JMWC1','TUOL'),
('JSDC1','TUOL'),
('KBAN','TUOL'),
('KIBC1','TUOL'),
('KO57','TUOL'),
('LELC1','TUOL'),
('LVTC1','TUOL'),
('MAMC1','TUOL'),
('MBBC1','TUOL'),
('MIIC1','TUOL'),
('MLHC1','TUOL'),
('MPOC1','TUOL'),
('OMMCA','TUOL'),
('OSTC1','TUOL'),
('PDSC1','TUOL'),
('PNCC1','TUOL'),
('PNWC1','TUOL'),
('POJC1','TUOL'),
('RELC1','TUOL'),
('SDWC1','TUOL'),
('SLIC1','TUOL'),
('SRAC1','TUOL'),
('TGCC1','TUOL'),
('THYC1','TUOL'),
('TIOC1','TUOL'),
('TS042','TUOL'),
('TUMC1','TUOL'),
('VGAC1','TUOL'),
('WWNC1','TUOL'),
('WWRC1','TUOL'),
('YVVC1','TUOL'),
('YWAC1','TUOL'),
('YYVC1','TUOL'),

-- UNCOMPAHGRE
('ANBC2','UNCOM'),
('CAABR','UNCOM'),
('CAEGE','UNCOM'),
('CAGDH','UNCOM'),
('CAKDL','UNCOM'),
('CAMLP','UNCOM'),
('CAMON','UNCOM'),
('CAPBA','UNCOM'),
('CAPTY','UNCOM'),
('CASBK','UNCOM'),
('CASWP','UNCOM'),
('CATEL','UNCOM'),
('CLOC2','UNCOM'),
('CO055','UNCOM'),
('D6226','UNCOM'),
('DCKC2','UNCOM'),
('DMSC2','UNCOM'),
('E0715','UNCOM'),
('EDSC2','UNCOM'),
('GBMC2','UNCOM'),
('IDRC2','UNCOM'),
('IROC2','UNCOM'),
('KTEX','UNCOM'),
('LIZC2','UNCOM'),
('LPSC2','UNCOM'),
('MINC2','UNCOM'),
('MLSC2','UNCOM'),
('PMSC2','UNCOM'),
('RMPC2','UNCOM'),
('SJAC2','UNCOM'),
('SMXC2','UNCOM'),
('UNRC2','UNCOM'),
('WRGC2','UNCOM');







