
CREATE DATABASE IF NOT EXISTS mdbutil;

GRANT RELOAD, LOCK TABLES, PROCESS, REPLICATION CLIENT ON *.* TO 'backupuser'@'localhost' IDENTIFIED BY 'KER6gH5Ab3piOfHoN7Jk';

GRANT ALL PRIVILEGES ON mdbutil.* TO 'backupuser'@'localhost';

FLUSH PRIVILEGES;
